version: '3.8'

services:
  app:
    image: nnplanner:latest
    container_name: nnplanner-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      LOCAL_DB_URL: ${LOCAL_DB_URL}
      LOCAL_DB_USER: ${LOCAL_DB_USER}
      LOCAL_DB_PASSWORD: ${LOCAL_DB_PASSWORD}
      LOCAL_MONGODB_URL: ${LOCAL_MONGODB_URL}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      GOOGLE_EMAIL: ${GOOGLE_EMAIL}
      GOOGLE_PASSWORD: ${GOOGLE_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      FOOD_API_KEY: ${FOOD_API_KEY}
      SCHOOL_API_KEY: ${SCHOOL_API_KEY}
    depends_on:
      - db
      - redis
      - mongodb-service

  db:
    image: postgres:latest
    container_name: nnplanner-db
    environment:
      POSTGRES_DB: nnplanner
      POSTGRES_USER: ${LOCAL_DB_USER}
      POSTGRES_PASSWORD: ${LOCAL_DB_PASSWORD}
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: nnplanner-redis
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "6379:6379"

  mongodb-service:
    image: mongo:latest
    container_name: mongodb-service
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27017:27017"

networks:
  default:
    name: nnplanner-network
