version: '3.8'

services:
  nnplanner-app:
    build:
      context: .
    environment:
      - LOCAL_DB_URL=${LOCAL_DB_URL}
      - LOCAL_DB_USER=${LOCAL_DB_USER}
      - LOCAL_DB_PASSWORD=${LOCAL_DB_PASSWORD}
      - LOCAL_MONGODB_URL=${LOCAL_MONGODB_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - GOOGLE_EMAIL=${GOOGLE_EMAIL}
      - GOOGLE_PASSWORD=${GOOGLE_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - FOOD_API_KEY=${FOOD_API_KEY}
      - SCHOOL_API_KEY=${SCHOOL_API_KEY}
    ports:
      - "8080:8080"
    depends_on:
      - nnplanner-db
      - mongodb-service
      - nnplanner-redis

  nnplanner-db:
    image: postgres:16
    environment:
      POSTGRES_DB: nnplanner
      POSTGRES_USER: ${LOCAL_DB_USER}
      POSTGRES_PASSWORD: ${LOCAL_DB_PASSWORD}
    ports:
      - "5432:5432"

  mongodb-service:
    image: mongo:8.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"

  nnplanner-redis:
    image: redis:7.4
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
