spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${PROD_DB_URL}
    username: ${PROD_DB_USER}
    password: ${PROD_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
    open-in-view: false

  data:
    mongodb:
      port: 27017
      database: ${PROD_MONGODB_URL}
      username: ${PROD_MONGODB_USER}
      password: ${PROD_MONGODB_PASSWORD}

jwt:
  secret:
    expiration-time: 60 * 60 * 1000L
    key: ${JWT_SECRET_KEY}